// import { Inter } from '@next/font/google'
import Dashboard from '@modules/Dashboard'
import Head from 'next/head'
// const inter = Inter({ subsets: ['latin'] })
import Layout from '@components/Layout'

export default function Home() {
  return (
    <>
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Dashboard />
      </main>
    </>
  )
}

Home.getLayout = function getLayout(page: JSX.Element) {
  return <Layout title="Dashboard">{page}</Layout>
}
